/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'published' : boolean,
  'author' : string,
  'image' : [] | [ExternalBlob],
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'specifications' : string,
  'productId' : bigint,
  'email' : string,
  'quantity' : bigint,
  'phone' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'image' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogPost' : ActorMethod<[string, string, string], bigint>,
  'createProduct' : ActorMethod<[string, string, string], bigint>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, string, bigint, string],
    bigint
  >,
  'submitContactForm' : ActorMethod<[string, string, string, string], bigint>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateProduct' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];